Repository bd-gg/bdgg-server, pull requests merged in 2020-05, with the labels that each got.

#3 [feat] add profile apis
  src/main/java/gg/boardgame/bdgg/controller/ProfileController.java
  src/main/java/gg/boardgame/bdgg/dto/GameHistoryDTO.java
  src/main/java/gg/boardgame/bdgg/dto/IndividualGameResultDTO.java
  src/main/java/gg/boardgame/bdgg/dto/MatchDTO.java
  src/main/java/gg/boardgame/bdgg/dto/ProfileDTO.java
  src/main/java/gg/boardgame/bdgg/service/ProfileService.java
  src/main/java/gg/boardgame/bdgg/service/ProfileServiceImpl.java
Labels: feat

#4 [feat] Add Entity(dto) classes
  src/main/java/gg/boardgame/bdgg/account/Account.java
  src/main/java/gg/boardgame/bdgg/account/AccountRepository.java
  src/main/java/gg/boardgame/bdgg/db/Group.java
  src/main/java/gg/boardgame/bdgg/db/GroupMember.java
  src/main/java/gg/boardgame/bdgg/db/GroupMemeberRepository.java
  src/main/java/gg/boardgame/bdgg/db/GroupRepository.java
  src/main/java/gg/boardgame/bdgg/db/Match.java
  src/main/java/gg/boardgame/bdgg/db/MatchRepository.java
  src/main/java/gg/boardgame/bdgg/db/User.java
  src/main/java/gg/boardgame/bdgg/db/UserGaemHistoryRepository.java
  src/main/java/gg/boardgame/bdgg/db/UserGameHistory.java
  src/main/java/gg/boardgame/bdgg/db/UserMatch.java
  src/main/java/gg/boardgame/bdgg/db/UserMatchRepository.java
  src/main/java/gg/boardgame/bdgg/db/UserRepository.java
Labels: feat

#6 Resolve#5 Refactoring suggestion
  .gitignore
  src/main/java/gg/boardgame/bdgg/db/Group.java
  src/main/java/gg/boardgame/bdgg/db/GroupMember.java
  src/main/java/gg/boardgame/bdgg/db/Match.java
  src/main/java/gg/boardgame/bdgg/db/User.java
  src/main/java/gg/boardgame/bdgg/db/UserGameHistory.java
  src/main/java/gg/boardgame/bdgg/db/UserMatch.java
  src/main/java/gg/boardgame/bdgg/dto/GameHistoryDTO.java
  src/main/java/gg/boardgame/bdgg/dto/IndividualGameResultDTO.java
  src/main/java/gg/boardgame/bdgg/dto/MatchDTO.java
  src/main/java/gg/boardgame/bdgg/dto/ProfileDTO.java
  src/main/resources/application.properties
Labels: refactor

#7 [test] Add JUnit test for UserRepository
  src/main/java/gg/boardgame/bdgg/db/UserRepository.java
  src/test/java/gg/boardgame/bdgg/account/AccountRepositoryTest.java
  src/test/java/gg/boardgame/bdgg/db/UserRepositoryTest.java
Labels: test

#8 Add service that return user match list
  src/main/java/gg/boardgame/bdgg/controller/ProfileController.java
  src/main/java/gg/boardgame/bdgg/db/Match.java
  src/main/java/gg/boardgame/bdgg/db/UserMatchRepository.java
  src/main/java/gg/boardgame/bdgg/dto/IndividualGameResultDTO.java
  src/main/java/gg/boardgame/bdgg/dto/MatchDTO.java
  src/main/java/gg/boardgame/bdgg/service/ProfileService.java
  src/main/java/gg/boardgame/bdgg/service/ProfileServiceImpl.java
Labels: feat

#9 Add test db data
  src/main/java/gg/boardgame/bdgg/BdggApplication.java
  src/main/java/gg/boardgame/bdgg/db/Group.java
  src/main/java/gg/boardgame/bdgg/db/GroupMember.java
  src/main/java/gg/boardgame/bdgg/db/GroupMemberRepository.java
  src/main/java/gg/boardgame/bdgg/db/Match.java
  src/main/java/gg/boardgame/bdgg/db/User.java
  src/main/java/gg/boardgame/bdgg/db/UserGameHistory.java
  src/main/java/gg/boardgame/bdgg/db/UserMatch.java
Labels: feat, refactor

#10 Add service that return profile info & most played game list
  src/main/java/gg/boardgame/bdgg/BdggApplication.java
  src/main/java/gg/boardgame/bdgg/controller/ProfileController.java
  src/main/java/gg/boardgame/bdgg/db/User.java
  src/main/java/gg/boardgame/bdgg/db/UserGaemHistoryRepository.java
  src/main/java/gg/boardgame/bdgg/db/UserGameHistory.java
  src/main/java/gg/boardgame/bdgg/db/UserGameHistoryRepository.java
  src/main/java/gg/boardgame/bdgg/db/UserMatchRepository.java
  src/main/java/gg/boardgame/bdgg/db/UserRepository.java
  src/main/java/gg/boardgame/bdgg/dto/ProfileDTO.java
  src/main/java/gg/boardgame/bdgg/service/ProfileService.java
  src/main/java/gg/boardgame/bdgg/service/ProfileServiceImpl.java
Labels: feat, refactor
